# --- CONFIGURAÇÃO STARSHIP GABRYEL (STEALTH + ICONS) ---

add_newline = false

# Ordem: OS -> Pasta -> Git Branch -> Git Status -> Símbolo
format = """
$os$directory$git_branch$git_status$character
"""

[os]
disabled = false
format = "[$symbol]($style) "
style = "bold blue"

[os.symbols]
Arch = " "
CachyOS = " "
Linux = " "

[directory]
style = "bold #e0e0e0"
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold white"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
# Removi os colchetes duplos que causaram o erro
format = "([$all_status$ahead_behind]($style) )"
modified = "*"
staged = "+"
untracked = "?"
deleted = "✘"

[character]
success_symbol = "[❯](bold #262626)"
error_symbol = "[❯](bold red)"